apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ascape-model
  namespace: kfserving-test
spec:
  default:
    predictor:
      custom:
        name: ascape-model
        container: 
          image: "dokeridforioana/ascape-predict:1.0.0"
