apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: model-m3
  namespace: kfserving-test
spec:
  predictor:
    containers:
      - name: model-m3
        image: "docker.io/dokeridforioana/ascape-predict:1.1.3"
        env:
           - name: MODEL_NAME 
             value: "model-m3"
        resources: 
         limits: 
           cpu: 25m
           memory: 1Gi
         requests:
           cpu: 25m
           memory: 100Mi
