apiVersion: apps/v1
kind: Deployment
metadata:
  name: ascape
spec:
  selector:
    matchLabels:
      app: ascape
  replicas: 1
  template:
    metadata:
      labels:
        app: ascape
    spec:
      imagePullSecrets:
      - name: registry.gitlab.ascape-h2020.cred
      containers:
      - name: ascape
        image: registry.gitlab.com/ascape-h2020/cloud/heredactedpatientdatamanager:test
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
        - name: APPLICATION_PORT
          value: "3000"
        - name: APPLICATION_HOST
          value: "0.0.0.0"
        - name: APPLICATION_DB_CONTAINER
          value: my-release-postgresql
        - name: ENVIRONEMENT
          value: DEV
        - name: APPLICATION_POSTGRES_PW
          valueFrom:
           secretKeyRef:
            name: postgressecret
            key: password
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio.kubeflow:9000
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
           secretKeyRef:
            name: miniosecret
            key: username
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
           secretKeyRef:
            name: miniosecret
            key: password
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow.ascape:5000
        - name: ML_PIPELINE_URI
          value: http://ml-pipeline.kubeflow:8888
        - name: CUSTOM_PREDICTION_URL
          value: http://custom-serving.ascape:3001
        resources:
          requests:
            cpu: "500m"
        

---
apiVersion: v1
kind: Service
metadata:
  name: ascape
  namespace: ascape
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: ascape
