apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: ascape-model
spec:
  predictor:
    containers:
      - name: ascape-model
        image: "dokeridforioana/ascape-predict:1.0.0"
