apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: ascape-model
  namespace: kfserving-test
spec:
  predictor:
    containers:
      - name: ascape-model
        image: "dokeridforioana/ascape-predict:1.0.6"
        resources: 
         limits: 
           cpu: 25m
           memory: 1Gi
         requests:
           cpu: 25m
           memory: 100Mi
