apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-serving
spec:
  selector:
    matchLabels:
      app: custom-serving
  replicas: 1
  template:
    metadata:
      labels:
        app: custom-serving
    spec:
      imagePullSecrets:
      - name: gitlab-auth
      containers:
      - name: custom-serving
        image: registry.gitlab.com/ascape-h2020/cloud/heaimodelsmanager/prediction:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3001
        env:
        - name: APPLICATION_PORT
          value: "3001"
        - name: APPLICATION_HOST
          value: "0.0.0.0"
        - name: ENVIRONEMENT
          value: DEV
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio.kubeflow:9000
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
           secretKeyRef:
            name: miniosecret
            key: username
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
           secretKeyRef:
            name: miniosecret
            key: password
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow.ascape:5000
        resources:
          requests:
            cpu: "500m"
        

---
apiVersion: v1
kind: Service
metadata:
  name: custom-serving
spec:
  ports:
  - port: 3001
    targetPort: 3001
    name: http
  selector:
    app: custom-serving
