apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ascape-model-01
  namespace: kfserving-ascape
spec:
  default:
    predictor:
      custom:
        name: ascape-model-01
        container: 
          image: "dokeridforioana/ascape-predict-image:1.0.1"
