apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "iris"
  namespace: "kfserving-test"
spec:
   predictor:
     sklearn:      
       resources: 
         limits: 
           cpu: 25m
           memory: 1Gi
         requests:
           cpu: 25m
           memory: 100Mi
       storageUri: "gs://kfserving-samples/models/sklearn/iris"
