apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: dokeridforioana/mlflow-server:1.0.1
        imagePullPolicy: Always
        args:
        - --host=0.0.0.0
        - --port=5000
        - --backend-store-uri=postgresql://postgres:gRgcWP198a@my-release-postgresql:5432/mlruns
        - --default-artifact-root=s3://ascape-models/
        - --workers=2
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio.kubeflow:9000
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
           secretKeyRef:
            name: miniosecret
            key: username
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
           secretKeyRef:
            name: miniosecret
            key: password
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: mlflow
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mlflow
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.il/add-base-url: "true"
spec:
  rules:
  - host: mlflow.local
    http:
      paths:
        - backend:
            serviceName: mlflow
            servicePort: 5000
          path: /
