apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: "kfserving-test"
spec:
   predictor:
     sklearn:      
       resources: 
         limits: 
           cpu: 1
           memory: 2Gi
         requests:
           cpu: 1
           memory: 2Gi
       storageUri: "gs://kfserving-samples/models/sklearn/iris"

