apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: "kfserving-test"
spec:
  default:
    predictor:
      sklearn:
        storageUri: "gs://kfserving-samples/models/sklearn/iris"
        resource: 
          limits: 
            cpu: 1
            memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi

