apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: "kfserving-ascape"
spec:
  predictor:
    SKLearn:
      storageUri: "gs://kfserving-samples/models/sklearn/iris"
